### ISSUE TITLE
Failed installing in FreeBSD 11

### ISSUE THREAD

**Issue by webching** [juce/sockproc#7]
# make
gcc49 -Wall -Werror -o sockproc sockproc.c
sockproc.c: In function 'main':
sockproc.c:304:35: error: invalid application of 'sizeof' to incomplete type 'struct sockaddr_in'
         memset(&addr_in, 0, sizeof(addr_in));
                                   ^
sockproc.c:305:9: error: invalid use of undefined type 'struct sockaddr_in'
         addr_in.sin_family = AF_INET;
         ^
sockproc.c:306:9: error: invalid use of undefined type 'struct sockaddr_in'
         addr_in.sin_port = htons(port);
         ^
sockproc.c:307:9: error: invalid use of undefined type 'struct sockaddr_in'
         addr_in.sin_addr.s_addr = inet_addr("127.0.0.1");
         ^
sockproc.c:308:56: error: invalid application of 'sizeof' to incomplete type 'struct sockaddr_in'
         if (bind(fd, (struct sockaddr*)&addr_in, sizeof(addr_in)) == -1) {
                                                        ^
*** Error code 1

Stop.

**Comment by juce** [comment]
hrm.. interesting. i guess some include is missing on FreeBSD 11
I'll try to make a vm and test. Thanks for reporting

**Comment by juce** [comment]
fixed the compile issues (and tests) on FreeBSD 11
commit:  75fd043331d91081e8850729bedb91f67abb3c82
